### ISSUE TITLE
Installed exec script assumes Dynawo is installed in same dir of Dynawo algorithms

### ISSUE THREAD

**Issue by zamarrenolm** [dynawo/dynawo-algorithms#18]
After build and install, the script to launch dynawo algorithms assumes that Dynawo installation dir is the same of the Dynawo Algorithms install dir.

In file: `execDynawoAlgorithms.sh`, the function `setEnv` sets:

```bash
DYNAWO_INSTALL_DIR=$DYNAWO_ALGORITHMS_INSTALL_DIR
```

But Dynawo could be installed in a different place ...

**Comment by gautierbureau** [comment]
`execDynawoAlgorithms.sh` is a ressource that is meant to be used once a distribution is produced and not when someone uses a development version. It is the equivalent of this file https://github.com/dynawo/dynawo/blob/master/dynawo/sources/Launcher/dynawo.sh. Maybe we should rename it in `dynawo-algorithms.sh` and add a comment to clarify its use.

**Comment by zamarrenolm** [comment]
> `execDynawoAlgorithms.sh` is a ressource that is meant to be used once a distribution is produced and not when someone uses a development version. It is the equivalent of this file https://github.com/dynawo/dynawo/blob/master/dynawo/sources/Launcher/dynawo.sh. Maybe we should rename it in `dynawo-algorithms.sh` and add a comment to clarify its use.

So you mean it is ok for this script to assume Dynawo installation dir == Dynawo Algorithms installation dir.

**Comment by gautierbureau** [comment]
> > `execDynawoAlgorithms.sh` is a ressource that is meant to be used once a distribution is produced and not when someone uses a development version. It is the equivalent of this file https://github.com/dynawo/dynawo/blob/master/dynawo/sources/Launcher/dynawo.sh. Maybe we should rename it in `dynawo-algorithms.sh` and add a comment to clarify its use.
> 
> So you mean it is ok for this script to assume Dynawo installation dir == Dynawo Algorithms installation dir.

Yes because it is the way the distribution zip will be organized
