### ISSUE TITLE
Build release for CI of dependant projects

### ISSUE THREAD

**Issue by zamarrenolm** [dynawo/dynawo-algorithms#83]
Build a nightly release that can be used for continuous integration of dependant projects (dynaflow-launcher, ...)

**Comment by gautierbureau** [comment]
The build failed and it seems it is related to the cxx11 abi forcing not working

**Comment by zamarrenolm** [comment]
> The build failed and it seems it is related to the cxx11 abi forcing not working

Yes, I am analyzing it. I was able to reproduce the error with dynawo/dynawo-algorithms; but it does not show up in zamarrenolm/dynawo-algorithms.  The contents of CMakeCache.txt are different:
```
diff -r dynawo-algorithms-zamarrenolm/build/gcc5.3.1/master/Release/dynawo-algorithms/CMakeCache.txt dynawo-algorithms-dynawo/build/gcc5.3.1/master/Release/dynawo-algorithms/CMakeCache.txt
320c320
< FORCE_CXX11_ABI:BOOL=true
---
> FORCE_CXX11_ABI:BOOL=OFF
```
But the workflow files are identical, the CMake input files are the same, and the docker image used is the same (dynawo/dynawo-distribution-cxx11:latest). I am trying to identify the cause of the difference.

**Comment by gautierbureau** [comment]
> > The build failed and it seems it is related to the cxx11 abi forcing not working
> 
> Yes, I am analyzing it. I was able to reproduce the error with dynawo/dynawo-algorithms; but it does not show up in zamarrenolm/dynawo-algorithms. The contents of CMakeCache.txt are different:
> 
> ```
> diff -r dynawo-algorithms-zamarrenolm/build/gcc5.3.1/master/Release/dynawo-algorithms/CMakeCache.txt dynawo-algorithms-dynawo/build/gcc5.3.1/master/Release/dynawo-algorithms/CMakeCache.txt
> 320c320
> < FORCE_CXX11_ABI:BOOL=true
> ---
> > FORCE_CXX11_ABI:BOOL=OFF
> ```
> 
> But the workflow files are identical, the CMake input files are the same, and the docker image used is the same (dynawo/dynawo-distribution-cxx11:latest). I am trying to identify the cause of the difference.

It seems the quote of $CMAKE_OPTIONAL does not behave well... We can delete it

**Comment by zamarrenolm** [comment]
ok, it is the only difference between the two repos

> > > The build failed and it seems it is related to the cxx11 abi forcing not working
> > 
> > 
> > Yes, I am analyzing it. I was able to reproduce the error with dynawo/dynawo-algorithms; but it does not show up in zamarrenolm/dynawo-algorithms. The contents of CMakeCache.txt are different:
> > ```
> > diff -r dynawo-algorithms-zamarrenolm/build/gcc5.3.1/master/Release/dynawo-algorithms/CMakeCache.txt dynawo-algorithms-dynawo/build/gcc5.3.1/master/Release/dynawo-algorithms/CMakeCache.txt
> > 320c320
> > < FORCE_CXX11_ABI:BOOL=true
> > ---
> > > FORCE_CXX11_ABI:BOOL=OFF
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But the workflow files are identical, the CMake input files are the same, and the docker image used is the same (dynawo/dynawo-distribution-cxx11:latest). I am trying to identify the cause of the difference.
> 
> It seems the quote of $CMAKE_OPTIONAL does not behave well... We can delete it

yes, it is the only difference between both versions.
